version: "3"

services:
  docs:
    build:
      context: ./test-env/node-dev
      args:
        TZ: Europe/Berlin
    user: "node"
    entrypoint: bash
    command:
      - "-c"
      - "pnpm i && npm run build && npm run coverage && compodoc"
    restart: "no"
    volumes:
      - .:/opt/slf4ts/
    working_dir: "/opt/slf4ts"

  deps:
    build:
      context: ./test-env/node-dev
      args:
        TZ: Europe/Berlin
    user: "node"
    entrypoint: bash
    command:
      - "-c"
      - "npm run deps"
    restart: "no"
    volumes:
      - .:/opt/slf4ts/
    working_dir: "/opt/slf4ts"
