packages:
  - examples/**
  - packages/**
  - '!**/example-node-modules/**'

allowBuilds:
  dtrace-provider: false
  esbuild: true

overrides:
  cassandra-driver>adm-zip: '>=0.6.0'
  mocha>serialize-javascript: '>=7.0.5'
