name: CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]
        os:
          #- windows-2022
          #- windows-2019
          #- macos-12
          #- macos-11
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v6
        with:
          run_install: |
            - recursive: true

      - name: Get pnpm store directory
        id: pnpm-store
        run: echo "path=$(pnpm store path)" >> "$GITHUB_OUTPUT"

      - name: Cache node modules
        uses: actions/cache@v6
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-${{ runner.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.node-version }}-build-${{ env.cache-name }}-

      - name: build
        run: pnpm run build

      - name: test
        run: pnpm run test
        env:
          CI: true
          TZ: Europe/Berlin
